### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by glennular**
Initial Demo PR.
After this, i'll just work out of master....

### CODE REVIEW

**Comment by surprisetalk** [comment]
Wow! Thanks for all the hard work.
The initial demo site looks amazing! I really want to help you fill out some of the pages this week :smiley_cat:

**Comment by surprisetalk** [comment]
Before that, I can't find any references to "has-shadow" or "navbar-tabs" in the official 0.6.2 docs. May I ask where you found them? I'm hesitant to include anything that the Bulma team hasn't put their stamp of approval on...

**Comment by glennular** [comment]
Thanks for pointing that out, that's why i didn't want to just merge.

To create the demo site, I essentially reverse engineered the Bulma Doc site, and I tried to match the headers to the site, not necessarily the documentation. I verified existence in the the css not the doc. So the styles are there, just not documented.

It seems that navbar-tabs is a carry over from the old nav component:
https://bulma.io/documentation/components/nav/
Some did make it to the variables section
https://bulma.io/documentation/components/navbar/#variables

They did add support, and documented some of the attributes but not all of them:
https://github.com/jgthms/bulma/issues/842

Same as has-shadow:
https://github.com/jgthms/bulma/issues/865

How did you want to move forward, I'm fine either way, i could pull them out and make a workaround, or we leave them, since they are in the css.

**Comment by surprisetalk** [comment]
That's a tough one. I really like your implementation, but I'm hesitant to add it because I don't want to make any breaking changes to the Elm package just yet. Can we stick the `navbar` and `has-shadow` changes in a separate branch for now? We can call it `navbar-extra` or something like that until we figure out what @jgthms is planning to do.

**Pull request merged**
